import requests
from bs4 import BeautifulSoup
import csv
from datetime import datetime

# list endpoints to scrape
endpoints = [
    "/aceh/banda-aceh",
    "/aceh/bireuen",
    "/aceh/gayo-lues",
    "/aceh/aceh-barat-daya",
    "/aceh/aceh-jaya",
    "/aceh/aceh-timur",
    "/aceh/aceh-tamiang",
    "/aceh/aceh-besar",
    "/aceh/aceh-tenggara",
    "/aceh/langsa",
    "/aceh/lhokseumawe",
    "/aceh/aceh-utara",
    "/aceh/aceh-barat",
    "/aceh/sabang",
    "/aceh/pidie",
    "/aceh/bener-meriah",
    "/aceh/simeulue",
    "/aceh/aceh-singkil",
    "/aceh/nagan-raya",
    "/aceh/aceh-tengah",
    "/aceh/aceh-selatan",
    "/aceh/pidie-jaya",
    "/aceh/subulussalam",
    "/bali/karangasem",
    "/bali/bangli",
    "/bali/denpasar",
    "/bali/gianyar",
    "/bali/badung",
    "/bali/jembrana",
    "/bali/klungkung",
    "/bali/buleleng",
    "/bali/tabanan",
    "/bangka-belitung/bangka-tengah",
    "/bangka-belitung/belitung-timur",
    "/bangka-belitung/bangka-barat",
    "/bangka-belitung/pangkalpinang",
    "/bangka-belitung/bangka",
    "/bangka-belitung/belitung",
    "/bangka-belitung/bangka-selatan",
    "/bangka-belitung/blinyu",
    "/bangka-belitung/bangka-barat",
    "/bangka-belitung/bangka-tengah",
    "/bangka-belitung/belitung",
    "/banten/a:0:{}",
    "/banten/cilegon",
    "/banten/pandeglang",
    "/banten/lebak",
    "/banten/serang",
    "/banten/tangerang",
    "/banten/serang",
    "/banten/merak",
    "/banten/cilegon",
    "/banten/pandeglang",
    "/banten/pandeglang",
    "/banten/lebak",
    "/banten/lebak",
    "/banten/lebak",
    "/banten/serang",
    "/banten/pandeglang",
    "/banten/lebak",
    "/banten/tangerang",
    "/banten/tangerang-selatan",
    "/banten/lebak",
    "/banten/serang",
    "/bengkulu/bengkulu-utara",
    "/bengkulu/bengkulu",
    "/bengkulu/kaur",
    "/bengkulu/rejang-lebong",
    "/bengkulu/kepahiang",
    "/bengkulu/bengkulu-selatan",
    "/bengkulu/muko-muko",
    "/bengkulu/seluma",
    "/bengkulu/lebong",
    "/bengkulu/bengkulu-tengah",
    "/yogyakarta/bantul",
    "/yogyakarta/sleman",
    "/yogyakarta/kulon-progo",
    "/yogyakarta/gunung-kidul",
    "/yogyakarta/yogyakarta",
    "/jakarta/jakarta-timur",
    "/jakarta/jakarta-barat",
    "/jakarta/jakarta-selatan",
    "/jakarta/kepulauan-seribu",
    "/jakarta/jakarta-pusat",
    "/jakarta/jakarta-utara",
    "/gorontalo/gorontalo",
    "/gorontalo/gorontalo",
    "/gorontalo/pahuwato",
    "/gorontalo/bone-bolango",
    "/gorontalo/boalemo",
    "/gorontalo/gorontalo-utara",
    "/gorontalo/gorontalo",
    "/jambi/merangin",
    "/jambi/batanghari",
    "/jambi/bungo",
    "/jambi/jambi",
    "/jambi/sungai-penuh",
    "/jambi/tanjung-jabung-barat",
    "/jambi/tanjung-jabung-timur",
    "/jambi/sarolangun",
    "/jambi/muaro-jambi",
    "/jambi/tebo",
    "/jambi/kerinci",
    "/west-java/bandung",
    "/west-java/banjar",
    "/west-java/ciamis",
    "/west-java/cianjur",
    "/west-java/bogor",
    "/west-java/bekasi",
    "/west-java/cimahi",
    "/west-java/cirebon",
    "/west-java/sukabumi",
    "/west-java/garut",
    "/west-java/indramayu",
    "/west-java/karawang",
    "/west-java/kuningan",
    "/west-java/majalengka",
    "/west-java/sukabumi",
    "/west-java/purwakarta",
    "/west-java/tasikmalaya",
    "/west-java/bandung",
    "/west-java/subang",
    "/west-java/cirebon",
    "/west-java/sumedang",
    "/west-java/tasikmalaya",
    "/west-java/bandung-barat",
    "/west-java/pelabuhan-ratu",
    "/west-java/bogor",
    "/west-java/bekasi",
    "/west-java/depok",
    "/west-java/pangandaran",
    "/west-java/bogor",
    "/west-java/cianjur",
    "/west-java/gadog-puncak",
    "/central-java/banjarnegara",
    "/central-java/batang",
    "/central-java/blora",
    "/central-java/boyolali",
    "/central-java/brebes",
    "/central-java/cilacap",
    "/central-java/demak",
    "/central-java/jepara",
    "/central-java/pekalongan",
    "/central-java/karanganyar",
    "/central-java/kebumen",
    "/central-java/kendal",
    "/central-java/klaten",
    "/central-java/kudus",
    "/central-java/magelang",
    "/central-java/magelang",
    "/central-java/pati",
    "/central-java/pekalongan",
    "/central-java/pemalang",
    "/central-java/purbalingga",
    "/central-java/grobogan",
    "/central-java/banyumas",
    "/central-java/purworejo",
    "/central-java/rembang",
    "/central-java/salatiga",
    "/central-java/semarang",
    "/central-java/tegal",
    "/central-java/sragen",
    "/central-java/sukoharjo",
    "/central-java/surakarta",
    "/central-java/tegal",
    "/central-java/temanggung",
    "/central-java/semarang",
    "/central-java/wonogiri",
    "/central-java/wonosobo",
    "/central-java/semarang",
    "/east-java/bangkalan",
    "/east-java/banyuwangi",
    "/east-java/batu",
    "/east-java/blitar",
    "/east-java/bojonegoro",
    "/east-java/bondowoso",
    "/east-java/gresik",
    "/east-java/jember",
    "/east-java/jombang",
    "/east-java/kediri",
    "/east-java/malang",
    "/east-java/lamongan",
    "/east-java/lumajang",
    "/east-java/madiun",
    "/east-java/madiun",
    "/east-java/magetan",
    "/east-java/malang",
    "/east-java/mojokerto",
    "/east-java/nganjuk",
    "/east-java/ngawi",
    "/east-java/pacitan",
    "/east-java/pamekasan",
    "/east-java/pasuruan",
    "/east-java/ponorogo",
    "/east-java/probolinggo",
    "/east-java/sampang",
    "/east-java/sidoarjo",
    "/east-java/situbondo",
    "/east-java/sumenep",
    "/east-java/surabaya",
    "/east-java/trenggalek",
    "/east-java/tuban",
    "/east-java/tulungagung",
    "/east-java/surabaya",
    "/east-java/kediri",
    "/east-java/mojokerto",
    "/east-java/probolinggo",
    "/east-java/blitar",
    "/east-java/pasuruan",
    "/west-kalimantan/bengkayang",
    "/west-kalimantan/ketapang",
    "/west-kalimantan/ngabang",
    "/west-kalimantan/pontianak",
    "/west-kalimantan/pontianak",
    "/west-kalimantan/sambas",
    "/west-kalimantan/sanggau",
    "/west-kalimantan/sekadau",
    "/west-kalimantan/singkawang",
    "/west-kalimantan/sintang",
    "/west-kalimantan/kubu-raya",
    "/west-kalimantan/kapuas-hulu",
    "/west-kalimantan/melawi",
    "/west-kalimantan/kayong-utara",
    "/west-kalimantan/kubu-raya",
    "/south-kalimantan/hulu-sungai-utara",
    "/south-kalimantan/banjarbaru",
    "/south-kalimantan/banjarmasin",
    "/south-kalimantan/tanah-bambu",
    "/south-kalimantan/hulu-sungai-tengah",
    "/south-kalimantan/hulu-sungai-selatan",
    "/south-kalimantan/kotabaru",
    "/south-kalimantan/barito-kuala",
    "/south-kalimantan/balangan",
    "/south-kalimantan/tanah-laut",
    "/south-kalimantan/tapin",
    "/south-kalimantan/tabalong",
    "/south-kalimantan/banjar",
    "/central-kalimantan/barito-selatan",
    "/central-kalimantan/katingan",
    "/central-kalimantan/kapuas",
    "/central-kalimantan/gunung-mas",
    "/central-kalimantan/seruyan",
    "/central-kalimantan/barito-utara",
    "/central-kalimantan/lamandau",
    "/central-kalimantan/palangkaraya",
    "/central-kalimantan/kotawaringin-barat",
    "/central-kalimantan/pulang-pisau",
    "/central-kalimantan/murung-raya",
    "/central-kalimantan/kotawaringin-timur",
    "/central-kalimantan/sukamara",
    "/central-kalimantan/barito-timur",
    "/central-kalimantan/sampit",
    "/east-kalimantan/balikpapan",
    "/east-kalimantan/bontang",
    "/east-kalimantan/penajam-paser-utara",
    "/east-kalimantan/samarinda",
    "/east-kalimantan/kutai-barat",
    "/east-kalimantan/kutai-timur",
    "/east-kalimantan/pasir",
    "/east-kalimantan/berau",
    "/east-kalimantan/kutai-kartanegara",
    "/east-kalimantan/balikpapan",
    "/east-kalimantan/nunukan",
    "/east-kalimantan/taraka",
    "/north-kalimantan/malinau",
    "/north-kalimantan/nunukan",
    "/north-kalimantan/bulungan",
    "/north-kalimantan/tarakan",
    "/north-kalimantan/tana-tidung",
    "/riau-islands/lingga",
    "/riau-islands/natuna",
    "/riau-islands/tanjung-pinang",
    "/riau-islands/anambas",
    "/riau-islands/batam",
    "/riau-islands/bintan",
    "/riau-islands/karimun",
    "/riau-islands/batam",
    "/riau-islands/tarempa",
    "/lampung/bandar-lampung",
    "/lampung/way-kanan",
    "/lampung/lampung-tengah",
    "/lampung/lampung-selatan",
    "/lampung/tanggamus",
    "/lampung/lampung-utara",
    "/lampung/lampung-barat",
    "/lampung/tulang-bawang",
    "/lampung/metro",
    "/lampung/lampung-timur",
    "/lampung/pesawaran",
    "/lampung/lampung-barat",
    "/lampung/tulang-bawang-barat",
    "/lampung/mesuji",
    "/lampung/pringsewu",
    "/maluku/ambon",
    "/maluku/seram-bagian-timur",
    "/maluku/kepulauan-aru",
    "/maluku/maluku-tengah",
    "/maluku/buru",
    "/maluku/seram-bagian-barat",
    "/maluku/maluku-tenggara-barat",
    "/maluku/maluku-tenggara",
    "/maluku/ambon",
    "/maluku/bula",
    "/maluku/dobo",
    "/maluku/namlea",
    "/maluku/saumlaki",
    "/maluku/tual",
    "/maluku/buru-selatan",
    "/maluku/maluku-barat-daya",
    "/north-maluku/halmahera-barat",
    "/north-maluku/halmahera-selatan",
    "/north-maluku/halmahera-timur",
    "/north-maluku/kepulauan-sula",
    "/north-maluku/ternate",
    "/north-maluku/halmahera-utara",
    "/north-maluku/halmahera-tengah",
    "/north-maluku/tidore-kepulauan",
    "/north-maluku/tidore-kepulauan",
    "/north-maluku/pulau-taliabu",
    "/north-maluku/pulau-morotai",
    "/west-nusa-tenggara/bima",
    "/west-nusa-tenggara/dompu",
    "/west-nusa-tenggara/lombok-barat",
    "/west-nusa-tenggara/mataram",
    "/west-nusa-tenggara/lombok-tengah",
    "/west-nusa-tenggara/lombok-timur",
    "/west-nusa-tenggara/sumbawa",
    "/west-nusa-tenggara/sumbawa-barat",
    "/west-nusa-tenggara/bima",
    "/west-nusa-tenggara/bima",
    "/west-nusa-tenggara/lombok-utara",
    "/east-nusa-tenggara/belu",
    "/east-nusa-tenggara/rote-ndao",
    "/east-nusa-tenggara/ngada",
    "/east-nusa-tenggara/ende",
    "/east-nusa-tenggara/alor",
    "/east-nusa-tenggara/timor-tengah-utara",
    "/east-nusa-tenggara/kupang",
    "/east-nusa-tenggara/manggarai-barat",
    "/east-nusa-tenggara/flores-timur",
    "/east-nusa-tenggara/lembata",
    "/east-nusa-tenggara/sikka",
    "/east-nusa-tenggara/manggarai",
    "/east-nusa-tenggara/timor-tengah-selatan",
    "/east-nusa-tenggara/sumba-barat",
    "/east-nusa-tenggara/sumba-timur",
    "/east-nusa-tenggara/manggarai-timur",
    "/east-nusa-tenggara/nagekeo",
    "/east-nusa-tenggara/sumba-tengah",
    "/east-nusa-tenggara/sumba-barat-daya",
    "/east-nusa-tenggara/ende",
    "/east-nusa-tenggara/kalabahi",
    "/east-nusa-tenggara/kupang",
    "/east-nusa-tenggara/larantuka",
    "/east-nusa-tenggara/loweleba",
    "/east-nusa-tenggara/maumere",
    "/east-nusa-tenggara/sumba-timur",
    "/east-nusa-tenggara/sabu-raijua",
    "/east-nusa-tenggara/malaka",
    "/east-nusa-tenggara/kupang",
    "/papua/asmat",
    "/papua/biak-numfor",
    "/papua/waropen",
    "/papua/paniai",
    "/papua/jayapura",
    "/papua/tolikara",
    "/papua/mappi",
    "/papua/merauke",
    "/papua/puncak-jaya",
    "/papua/nabire",
    "/papua/pegunungan-bintang",
    "/papua/sarmi",
    "/papua/jayapura",
    "/papua/kep-yapen",
    "/papua/supiori",
    "/papua/yahukimo",
    "/papua/boven-digoel",
    "/papua/mimika",
    "/papua/jayawijaya",
    "/papua/keerom",
    "/papua/mamberamo-raya",
    "/papua/agats",
    "/papua/biak",
    "/papua/jayapura",
    "/papua/merauke",
    "/papua/nabire",
    "/papua/serui",
    "/papua/jayapura",
    "/papua/deiyai",
    "/papua/deiyai",
    "/papua/intan-jaya",
    "/papua/keerom",
    "/papua/kepulauan-yapen",
    "/papua/lanny-jaya",
    "/papua/mamberamo-raya",
    "/papua/mamberamo-raya",
    "/papua/mamberamo-raya",
    "/papua/mimika",
    "/papua/nduga",
    "/papua/pegunungan-bintang",
    "/papua/waropen",
    "/papua/yalimo",
    "/papua/jayapura-",
    "/papua/supiori-",
    "/papua/nabire",
    "/papua/kepulauan-yapen-",
    "/papua/keerom-",
    "/papua/deiyai",
    "/papua/dogiyai",
    "/papua/lanny-jaya-",
    "/papua/puncak-",
    "/papua/intan-jaya-",
    "/papua/tolikara-",
    "/papua/puncak-jaya-",
    "/papua/jayawijaya-",
    "/papua/yalimo",
    "/papua/ndunga-",
    "/papua/yahukimo-",
    "/papua/pegunungan-bintang-",
    "/papua/mimika-",
    "/papua/asmat",
    "/papua/boven-digoel---tanah-merah",
    "/papua/sarmi",
    "/papua/merauke",
    "/west-papua/sorong",
    "/west-papua/teluk-bintuni",
    "/west-papua/fakfak",
    "/west-papua/kaimana",
    "/west-papua/manokwari",
    "/west-papua/sorong",
    "/west-papua/sorong-selatan",
    "/west-papua/raja-ampat",
    "/west-papua/teluk-wondama",
    "/west-papua/kaimana",
    "/west-papua/manokwari",
    "/west-papua/sorong",
    "/west-papua/wasior",
    "/west-papua/maybrat",
    "/west-papua/manokwari-selatan",
    "/riau/rokan-hilir",
    "/riau/kampar",
    "/riau/bengkalis",
    "/riau/dumai",
    "/riau/pelalawan",
    "/riau/rokan-hulu",
    "/riau/pekanbaru",
    "/riau/indragiri-hulu",
    "/riau/siak",
    "/riau/kuantan-singingi",
    "/riau/indragiri-hilir",
    "/riau/kepulauan-meranti",
    "/west-sulawesi/majene",
    "/west-sulawesi/mamasa",
    "/west-sulawesi/mamuju",
    "/west-sulawesi/mamuju-utara",
    "/west-sulawesi/polewali-mandar",
    "/west-sulawesi/mamuju-tengah",
    "/south-sulawesi/bantaeng",
    "/south-sulawesi/barru",
    "/south-sulawesi/kepulauan-selayar",
    "/south-sulawesi/bulukumba",
    "/south-sulawesi/enrekang",
    "/south-sulawesi/jeneponto",
    "/south-sulawesi/tana-toraja",
    "/south-sulawesi/makasar",
    "/south-sulawesi/luwu-timur",
    "/south-sulawesi/maros",
    "/south-sulawesi/luwu-utara",
    "/south-sulawesi/palopo",
    "/south-sulawesi/pare-pare",
    "/south-sulawesi/pinrang",
    "/south-sulawesi/toraja-utara",
    "/south-sulawesi/wajo",
    "/south-sulawesi/sidenreng-rappang",
    "/south-sulawesi/sinjai",
    "/south-sulawesi/gowa",
    "/south-sulawesi/takalar",
    "/south-sulawesi/bone",
    "/south-sulawesi/soppeng",
    "/south-sulawesi/barru",
    "/south-sulawesi/pangkajene-dan-kepulauan",
    "/central-sulawesi/tojo-una-una",
    "/central-sulawesi/morowali",
    "/central-sulawesi/buol",
    "/central-sulawesi/donggala",
    "/central-sulawesi/banggai",
    "/central-sulawesi/parigi-moutong",
    "/central-sulawesi/poso",
    "/central-sulawesi/banggai-kepulauan",
    "/central-sulawesi/toli-toli",
    "/central-sulawesi/banggai",
    "/central-sulawesi/kolonedale",
    "/central-sulawesi/luwuk",
    "/central-sulawesi/poso",
    "/central-sulawesi/palu",
    "/central-sulawesi/sigi-biromaru",
    "/southeast-sulawesi/konawe-selatan",
    "/southeast-sulawesi/bau---bau",
    "/southeast-sulawesi/kendari",
    "/southeast-sulawesi/kolaka",
    "/southeast-sulawesi/kolaka-utara",
    "/southeast-sulawesi/buton",
    "/southeast-sulawesi/muna",
    "/southeast-sulawesi/bombana",
    "/southeast-sulawesi/wakatobi",
    "/southeast-sulawesi/buton-utara",
    "/southeast-sulawesi/konawe",
    "/southeast-sulawesi/konawe-utara",
    "/southeast-sulawesi/kendari",
    "/southeast-sulawesi/raha",
    "/north-sulawesi/minahasa-utara",
    "/north-sulawesi/minahasa-selatan",
    "/north-sulawesi/bitung",
    "/north-sulawesi/bolaang-mongondow",
    "/north-sulawesi/manado",
    "/north-sulawesi/talaud",
    "/north-sulawesi/sangihe",
    "/north-sulawesi/minahasa",
    "/north-sulawesi/kotamobagu",
    "/north-sulawesi/sitaro",
    "/north-sulawesi/minahasa-tenggara",
    "/north-sulawesi/tahuna",
    "/north-sulawesi/bolaang-mongondow",
    "/north-sulawesi/tomohon",
    "/west-sumatra/solok",
    "/west-sumatra/tanah-datar",
    "/west-sumatra/bukittinggi",
    "/west-sumatra/agam",
    "/west-sumatra/pasaman",
    "/west-sumatra/sijunjung",
    "/west-sumatra/padang",
    "/west-sumatra/solok-selatan",
    "/west-sumatra/padangpanjang",
    "/west-sumatra/pesisir-selatan",
    "/west-sumatra/pariaman",
    "/west-sumatra/padang-pariaman",
    "/west-sumatra/payakumbuh",
    "/west-sumatra/dharmasraya",
    "/west-sumatra/limapuluh-kota",
    "/west-sumatra/sawahlunto",
    "/west-sumatra/pasaman-barat",
    "/west-sumatra/solok",
    "/west-sumatra/kepulauan-mentawai",
    "/south-sumatra/ogan-komering-ulu",
    "/south-sumatra/ogan-ilir",
    "/south-sumatra/lahat",
    "/south-sumatra/lubuk-linggau",
    "/south-sumatra/muaraenim",
    "/south-sumatra/ogan-komering-ulu-selatan",
    "/south-sumatra/musi-rawas",
    "/south-sumatra/pagar-alam",
    "/south-sumatra/palembang",
    "/south-sumatra/banyuasin",
    "/south-sumatra/prabumulih",
    "/south-sumatra/musi-banyuasin",
    "/south-sumatra/empat-lawang",
    "/south-sumatra/ogan-komering-ilir",
    "/south-sumatra/ogan-komering-ulu-timur",
    "/south-sumatra/penukal-abab-lematang-ilir",
    "/south-sumatra/musi-rawas-utara",
    "/north-sumatra/tebing-tinggi",
    "/north-sumatra/toba-samosir",
    "/north-sumatra/binjai",
    "/north-sumatra/humbang-hasundutan",
    "/north-sumatra/nias",
    "/north-sumatra/karo",
    "/north-sumatra/asahan",
    "/north-sumatra/deli-serdang",
    "/north-sumatra/medan",
    "/north-sumatra/padang-sidempuan",
    "/north-sumatra/tapanuli-tengah",
    "/north-sumatra/samosir",
    "/north-sumatra/mandailing-natal",
    "/north-sumatra/simalungun",
    "/north-sumatra/pematang-siantar",
    "/north-sumatra/labuhanbatu",
    "/north-sumatra/pak-pak-bharat",
    "/north-sumatra/serdang-bedagai",
    "/north-sumatra/sibolga",
    "/north-sumatra/dairi",
    "/north-sumatra/tapanuli-selatan",
    "/north-sumatra/langkat",
    "/north-sumatra/tanjung-balai",
    "/north-sumatra/tapanuli-utara",
    "/north-sumatra/nias-selatan",
    "/north-sumatra/batubara",
    "/north-sumatra/labuhanbatu-selatan",
    "/north-sumatra/labuhanbatu-utara",
    "/north-sumatra/padanglawas",
    "/north-sumatra/tapanuli-selatan",
    "/north-sumatra/nias-utara",
    "/north-sumatra/nias-barat",
]

# Base URL of IQAir website
url = 'https://www.iqair.com/id/indonesia'
dataBuffer = []

def format_id(kota, date):
    date_obj = datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
    formatted_date = date_obj.isoformat()
    return kota + "_" + formatted_date

def scrape(endpoint, time=datetime.now().strftime("%Y-%m-%d %H:%M:%S")):
    response = requests.get(url + endpoint)
    print("Scraping " + url + endpoint)
    # Check if the request was successful (status code 200)
    try:
        if response.status_code == 200:
        # Parse HTML content
            soup = BeautifulSoup(response.text, 'html.parser')
            title = soup.find('h1', class_='pagetitle__title').contents[0]
            index = soup.find('p', class_='aqi-value__value').contents[0]
            city = soup.find('a', class_="breadcrumb__item is-active").get_text()
            city = city.replace("Kota ", "").replace("Kab. ", "")
            city = city.strip()
            table_element = soup.find('table', attrs={'_ngcontent-airvisual-web-c224': ""})
            wind = "0 km/h"
            pressure = "0 mbar"
            for td in table_element.find_all('td'):
                if ("mbar" in td.text):
                    pressure = td.text
                if ("km/h" in td.text):
                    wind = td.text
            icon_parent = soup.find('img', class_="forecast-wind_icon")
            wind_dir = icon_parent.get('alt')
            
            # Print the extracted data
            print("=====================================")
            print('Title:', title)
            print('Index:', index)
            print('City:', city)
            print('Wind Direction:', wind_dir)
            print('Wind Speed:', wind)
            print('Wind Pressure:', pressure)
            print('Last Update:', time)
            print("=====================================")

            # append to buffer
            dataBuffer.append({
                'id': format_id(city, time),
                'kota': city,
                'iqa': index,
                'wind_dir(deg)': wind_dir,
                'wind_spd(km/h)': wind,
                'pressure(mbar)': pressure,
                'last_update': time
            })

        else:
            print('Failed to retrieve the webpage. Returning nulls.')
            dataBuffer.append({
                'id': format_id(city, time),
                'kota': city,
                'iqa': "",
                'wind_dir(deg)': "",
                'wind_spd(km/h)': "",
                'pressure(mbar)': "",
                'last_update': time
            })
            
    except:
        print('Error Occured.')

for endpoint in endpoints:
    scrape(endpoint)
    
# Write the extracted data to a CSV file
iter = 0
with open('csv/raw-iqair.csv', mode='w') as csv_file:
    fieldnames = ['id', 'kota', 'iqa', 'wind_dir(deg)', 'wind_spd(km/h)', 'pressure(mbar)', 'last_update']
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    try:
        writer.writeheader()
        for data in dataBuffer:
            writer.writerow(data)
            iter += 1
        print("Successfully wrote " + str(iter) + " non-null rows to CSV file.")
    except csv.Error as e:
        print("Error writing to CSV file.")
        print(e)